# Generated by Django 4.1.4 on 2022-12-22 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galaxy_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetPrefab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('prefab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planets.planetprefab')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='galaxy_map.system')),
            ],
        ),
    ]
